# 在kubernetes中，还存在一种和ConfigMap非常类似的对象，称为Secret对象。
# 它主要用于存储敏感信息，例如密码、秘钥、证书等等。
# 首先使用base64对数据进行编码
# $echo -n 'admin' | base64 #准备username
# YWRtaW4=
# $echo -n '123456' | base64 #准备password
# MTIzNDU2

apiVersion: v1
kind: Secret
metadata:
  name: secret
  namespace: dev
type: Opaque
data:
  username: YWRtaW4=
  password: MTIzNDU2
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-secret
  namespace: dev
spec:
  containers:
    - name: nginx
      image: nginx:1.17.1
      volumeMounts: # 将secret挂载到目录
        - name: config
          mountPath: /secret/config
  volumes:
    - name: config
      secret:
        secretName: secret
